version: 2.0
jobs:
  test:
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - run:
          name: coverage
          command: yarn coverage
      - run:
          name: prettier
          command: yarn prettier:check
workflows:
  version: 2
  test:
    jobs:
      - test
